name: Auto merge feature to develop

on:
  push:
    branches:
      - "HU**"

jobs:
  FusionarRamas:
    if: ${{ contains(github.event.head_commit.message, 'merge') }}
    name: FusionarRamas
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Merge develop to feature
        uses: tukasz/direct-merge-action@v2.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}

      - name: Checkout de repositorio
        uses: actions/checkout@v3

      - name: Configuración de entorno de Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Instalación de librerías y dependencias
        run:  npm install

      - name: Correr pruebas Unitarias
        run:  npm test -- --watch=false --browsers=ChromeHeadless

      - name: Correr pruebas e2e
        uses: cypress-io/github-action@v5
        with:
          start: npm run start
          browser: chrome
          wait-on: 'http://localhost:4200/en'


  Automerge:
    name: Automerge
    needs: FusionarRamas
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Merge feature to develop
        uses: tukasz/direct-merge-action@v2.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop

