name: Pull request to main

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ main ]

jobs:

  EjecutaPruebas:
    name: EjecutaPruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3

    - name: Configuración de entorno de Node
      uses: actions/setup-node@v3
      with:
         node-version: 14.x

    - name: Instalación de librerías y dependencias
      run: npm install

    - name: Correr pruebas
      run:  npm test -- --watch=false --browsers=ChromeHeadless

    - name: Cálculo de cubrimiento
      run: ng test --no-watch --code-coverage
