name: Angular CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        env:
          cache-name: cache-node-modules
        with:
            node-version: 14.x

      - name: Setup
        run: npm ci
      - name: Test
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless

