name: Angular CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - name: Setup
        run: npm install
      - name: Test
        run: npm test -- --configuration=ci

